apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: knote

build:
  artifacts:
    - image: knote
      context: .
      jib: {}

deploy:
  kustomize:
    paths:
      - kustomization/base

profiles:
  # Local cluster - we build and deploy things locally
  - name: local
    build:
      local:
        push: false
    activation:
      - kubeContext: docker-desktop
