# nonk8s
apiVersion: skaffold/v2beta23
kind: Config

metadata:
  name: knote

build:
  artifacts:
    - image: abyssspecies/knote:0.0.1
      context: .
      jib: {}

deploy:
  kustomize:
    paths:
      - kustomization/base

profiles:
  # Local cluster - we build and deploy things locally
  - name: local
    build:
      local:
        push: false
    activation:
      - kubeContext: docker-desktop
